name: Tests

on:
  push:
    paths:
      - "include/**"
      - "src/**"
      - "tests/**"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "include/**"
      - "src/**"
      - "tests/**"
      - ".github/workflows/test.yml"

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/build --target unit-tests
      - name: Run tests
        run: cd ${{github.workspace}}/build && ctest --output-on-failure
